### ISSUE TITLE
Sounds interesting

### ISSUE THREAD

**Issue by fullofcaffeine** [DoclerLabs/hexMachina#1]
So, saw the title of your talk in the WWX2016 official mkt site, and couldn't help but Google :) 

Would you mind sharing a bit about this framework? Is it a web framework?

Cheers!

**Comment by aliokan** [comment]
Hello, 

You can find some information about the framework on your new blog : http://hexmachina.org/
Documentation is very light for now, we working on it, but you can find a lot information in Unit Test on each package : [HexCoreSuite](https://github.com/DoclerLabs/hexCore/tree/master/test/hex), [HexInjectSuite](https://github.com/DoclerLabs/hexInject/tree/master/test/hex), [HexServiceSuite](https://github.com/DoclerLabs/hexService/tree/master/test/hex), [HexMVCSuite](https://github.com/DoclerLabs/hexMVC/tree/master/test/hex), [HexIoCSuite](https://github.com/DoclerLabs/hexIoC/tree/master/test/hex), [HexStateSuite](https://github.com/DoclerLabs/hexState/tree/master/test/hex/state), [HexUnitSuite](https://github.com/DoclerLabs/hexUnit/tree/master/test/hex)

[HexMVCSuite](https://github.com/DoclerLabs/hexMVC/tree/master/test/hex) and [HexIoCSuite](https://github.com/DoclerLabs/hexIoC/tree/master/test/hex) should be the most interesting suite to start. 

You can also look through our two MVC implementations in simple gallery project : 
[hexMachina-Gallery-Classical-MVC](https://github.com/DoclerLabs/hexMachina-Gallery-Classical-MVC)
[hexMachina-Gallery-Experimental-MVC](https://github.com/DoclerLabs/hexMachina-Gallery-Experimental-MVC)

And not lose this afternoon (15:15CET), the Francis talk about the framework at WWX2016 : http://wwx.silexlabs.org/2016/ 

Cheers!
