### ISSUE TITLE
Annotation not working in AsyncCommand from Macro

### ISSUE THREAD

**Issue by aliokan** [DoclerLabs/hexMachina#102]
Annotation seems not working in ~~Command~~ AsyncCommand added in Macro. 

In this example : https://github.com/aliokan/hexSandbox/blob/test/annotation-in-command-from-macro/src/configuration/context.xml

MacroWithAnnotation get Annotation, but CommandWithAnnotation not.

**Comment by FrancisBourre** [comment]
Thanks for the nice report and the time you took to reproduce and isolate this bug.

**Comment by FrancisBourre** [comment]
If you have an idea why this test was UTR your issue?
