### ISSUE TITLE
Support for typed maps

### ISSUE THREAD

**Issue by st3veV** [DoclerLabs/hexMachina#142]
Currently every HashMap defined in DSL is typed as `HashMap<Dynamic, Dynamic>`.
It'd be very useful to  be able to specify custom key and value types either as part of the type itself

``` xml
<collection id="fruits" type="hex.collection.HashMap<KeyType, ValueType>">
</collection>
```

or in more verbose way

``` xml
<collection id="fruits" type="hex.collection.HashMap" key-type="KeyType" value-type="ValueType">
</collection>
```

**Comment by Neverbirth** [comment]
I'd say this is a duplicate of #74.
