### ISSUE TITLE
Optimize the JS output for minifying

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMachina#153]
Right now we rely on standard javascript minifiers, but they cannot deal with the long class names (they keep it long). We need to find the way to minify perfectly the javascript output.

There are two possible proposal:
- Extamine why the minifiers fail to rename these classes, and change the output if it's possible
- Minifier macro, that renames every class before compilation to A, AA, AB, etc
- Independent tool that minifies perfectly the hexMachina generated JS code

**Comment by FrancisBourre** [comment]
We made a test with Closure compiler and it works fine for now. Btw, it fails in advanced mode. The idea is to make a fixed and cached version for advanced mode soon.

**Comment by grosmar** [comment]
Ok, sounds good for first. I close it for now
