### ISSUE TITLE
XmlCompiler.readXmlFileWithAssembler creates new compile-time assembler instance each time

### ISSUE THREAD

**Issue by aismagulov** [DoclerLabs/hexMachina#158]
Let's say we have context1.xml and context2.xml.
I was trying to parse them at compile time two XMLs within one context. 

```
var applicationAssembler: ApplicationAssembler = new ApplicationAssembler();
XmlCompiler.readXmlFileWithAssembler(applicationAssembler, "context1.xml");
XmlCompiler.readXmlFileWithAssembler(applicationAssembler, "context2.xml");
```

The problem is that for compile-time asssembling XmlCompiler.readXmlFileWithAssembler creates new CompileTimeApplicationAssembler on each call. Therefore created objects from different XMLs can't see each other.

So we need to be able to specify, whether we want to use the same compile-time assembler for separate XMLs, or not.

**Comment by FrancisBourre** [comment]
I just figured out that `extend` keyword addition solves this problem now. Later we should deprecate the old compilers for this kind of use, I mean they were not designed for that, and just keep them as compiler that are able to work with readers.

**Comment by FrancisBourre** [comment]
I close it for now.
