### ISSUE TITLE
Allow later addition of fields with Inject metadata

### ISSUE THREAD

**Issue by st3veV** [DoclerLabs/hexMachina#173]
Currently if build macro creates a field (or anything else that can be used for dependency injection) with `Inject` metadata it's not properly reflected because the reflection is already done.

Possible solution - Expose API to rerun reflection at compile time on a type that has already been reflected and append new reflection data.

**Comment by FrancisBourre** [comment]
That's possible to regenerate class reflection by passing fields to FastAnnotationReader like shown below:

```haxe
FastAnnotationReader.reflect( macro hex.di.IInjectorContainer, fields );
```

**Comment by st3veV** [comment]
`FastAnnotationReader.reflect( macro hex.di.IInjectorContainer, fields );` Seems to have a bug because it's removing the previous reflected data so running this twice completely strips out everything that was reflected.
