### ISSUE TITLE
Command executor fails with cryptic error

### ISSUE THREAD

**Issue by st3veV** [DoclerLabs/hexMachina#174]
When command is mapped to a event which is dispatched with generic payload (Array<Dynamic> as API suggests), CommandExecutor fails with error: 
`TypeError: request.getExecutionPayloads is not a function`

Either improve error reporting, or change API to make it more clear what's allowed to dispatch.

**Comment by FrancisBourre** [comment]
This one will go to the cemetery, hexIoC is deprecated, and hexCommand doesn't use this flow design anymore.
