### ISSUE TITLE
Enum reference support in DSL

### ISSUE THREAD

**Issue by st3veV** [DoclerLabs/hexMachina#215]
There is still a question how to deal with enum cunstructor parameters but for now at least having a possibility to reference trivial enums would be nice.

Code:
```haxe
enum Color
{
  Red;
  Green;
  Blue;
}

class ColorableClass
{
  new(color:Color)
  {
    //do something
  }
}
```

DSL:
```xml
<model id="redModel" type="ColorableClass">
  <argument static-ref="Color.Red" /><!-- doesn't work because Color.Red isn't a String -->
  <!--
  possible alternative to make clear we're working with enum:
  <argument enum-ref="Color.Red" />
  -->
</model>
```

**Comment by aliokan** [comment]
Can I abuse and request it for 0.29.0 @FrancisBourre ? ;-)

**Comment by FrancisBourre** [comment]
Sounds like it's already working with [flow](https://github.com/DoclerLabs/hexDSL/commit/c4ea9ee73cb25f208666af5fcd9a6c950f38ca97)
Do you need something special?

**Comment by aliokan** [comment]
I was tested in XML ^^
Is it difficult to add support to BasicStaticXmlCompiler too?

**Comment by FrancisBourre** [comment]
If it's needed, nothing is impossible. Just tell me. :)

**Comment by FrancisBourre** [comment]
Btw, believe or not, [it's already working with xml](https://github.com/DoclerLabs/hexDSL/commit/3dc2c35bd9425fad932bd3bd7b4404aa52643b5e)
