### ISSUE TITLE
Problem with withClassName

### ISSUE THREAD

**Issue by NewKrok** [DoclerLabs/hexMachina#216]
I can't create ExecutionPayload with UInt, but it works well with Int.

new ExecutionPayload( value ).withClassName( "UInt" )

Error:
hex.error.IllegalArgumentException at hex.control.payload.ExecutionPayload#withClassName line:78 in file 'ExecutionPayload.hx' | type 'UInt' not found [NoDomain] at hex.error.Exception::new line 24 in file Exception.hx

**Comment by FrancisBourre** [comment]
Should be fixed in next version. Func tests are passing.
