### ISSUE TITLE
Duplicate logger property

### ISSUE THREAD

**Issue by st3veV** [DoclerLabs/hexMachina#223]
If a property called `logger` which with a type different than `ILogger` exists in a class which implements `IsLoggable` and there is no other property of type `ILogger` there will be a duplicate `logger` field - one existing and one generated by the `IsLoggable`.

**Comment by FrancisBourre** [comment]
When you implement `IsLoggable`, the code generator checks if a propoerty already exists and uses it if that's the case. No more property duplication happens anymore.
