### ISSUE TITLE
Optional inject without param

### ISSUE THREAD

**Issue by NewKrok** [DoclerLabs/hexMachina#237]
It will be great if I could set an **Injection** to **Optional** without any params, like this:

```
@Optional // Instead of @Optional(true)
@Inject("someAwesomeClass")
public var someAwesomeClass:ISomeAwesomeClass
```

**Comment by aliokan** [comment]
https://github.com/DoclerLabs/hexAnnotation/commit/39e872f3cb4bb984cc43a2a5f37a72780bf6abf9
