### ISSUE TITLE
No type check for vars which injected by mappingDefinition

### ISSUE THREAD

**Issue by dmitry-kuzovatkin** [DoclerLabs/hexMachina#246]
if we need/can add type check for values which injecting by MappingDefinition?

dependencies = new Array<hex.di.mapping.MappingDefinition>(
  mapping({fromType: "String", toValue: o.value, withName: "value"})
);

In current case o.value is Int, but in code it injected as string without any warnings.

**Comment by Neverbirth** [comment]
Adding my +1.
