### ISSUE TITLE
MappingDefinition cannot handle fromType:"Bool->tink.CoreApi.Promise<swagger.model.BalanceResponse>"

### ISSUE THREAD

**Issue by aismagulov** [DoclerLabs/hexMachina#250]
Flow mapping:
`mapping({fromType: "Bool->tink.CoreApi.Promise<swagger.model.BalanceResponse>", toValue: balanceModel.fetchBalance})`

Module mappting:
`@Dependency(var _:Bool->Promise<BalanceResponse>)`

Error:
Missing mappings:[Bool->tink.CoreApi.BalanceResponse>|]

Which is especially strange, because there is no tink.CoreApi.BalanceResponse class mentioned anywhere.

**Comment by aliokan** [comment]
fixed with DoclerLabs/hexCore@14d09b000e07ef334bf9935424b6509d806d6227
