### ISSUE TITLE
@Optional inside of a function of ICommandTrigger causes problem

### ISSUE THREAD

**Issue by aismagulov** [DoclerLabs/hexMachina#255]
```
class MyClass implements ICommandTrigger
{
	public function myFunc():Void
	{
		@Inject("myModule")
		@Optional
		var myModule:MyModule;
		myModule.foo();
	}
}
```

gives an error "Local variable myModule used without being initialized".

**Comment by aliokan** [comment]
DoclerLabs/hexAnnotation@b34cb161c6a6d463e2620b9256a87767080d83b8
DoclerLabs/hexInject@0bad1bed9131448952850e39a72130df574b0816
DoclerLabs/hexMVC@da13deeb8e2e12ec651e92043743a3fd8562d7e4
