### ISSUE TITLE
CPU spike

### ISSUE THREAD

**Issue by peteshand** [DoclerLabs/hexMachina#265]
Hey there

I'm evaluating hexInject for an upcoming project. Looks like a cool project, however I've found that when I use the Inject class there is a large CPU spike.
![hexinject](https://user-images.githubusercontent.com/139457/36531710-e1ceccdc-1812-11e8-9acb-0423ba099b2d.JPG)
To be fair I am mapping about 15 classes in this one frame, but it still seems to take a lot longer than I would expect. Anyway is this normal? or am I missing some configuration to have code executed at compile time instead of runtime?

**Comment by st3veV** [comment]
Hey Pete,
thanks for the report.
Can you tell what version of hexMachina/hexInject is used?
Latest versions of the framework should precompile as much as possible and from the screenshot I can see that most of the time is spent on reflection which shouldn't be the case since version 0.33.0.

**Comment by peteshand** [comment]
Hey, thanks for the fact reply.. I'm not at my computer right now, but will check tomorrow... but in short this looks abnormal right?

**Comment by st3veV** [comment]
It looks very abnormal for current versions... for older versions which used reflection it looks a bit odd as well but it doesn't look particularly surprising because we're only actively using the JS target so we don't really benchmark other platforms.

**Comment by FrancisBourre** [comment]
Hi, thanks for the feedback. Would be great to hear your results on the flash platform with the latest release.

**Comment by FrancisBourre** [comment]
Prefer 0.34 (or even better 0.35) to 0.33, it's got latest additions for injection engine you don't want to miss:

- We don't print anymore reflection data in exported code except with #debugReflection compiler argument.
- Old annotation system removed (13 classes).
- Old injectors classes removed. (44 classes).
- During reflection merging we get rid of duplicated existing data and we keep super constructor data only if there's no constructor data available.
- Injector generated methods are saved from DCE.

**Comment by peteshand** [comment]
Apologies for not getting back to you on this.
So I was using a fairly old version .2x
Upgrading did help, I'm still seeing a CPU spike, however it's currently staying with the frame budget

**Comment by st3veV** [comment]
Thanks for the feedback. I think you'll always see some spike because everything gets instantiated and wired together at the same time. There's a way to avoid this heavy load with `@lazy` feature in DSL but this doesn't exist directly in the injector.
