### ISSUE TITLE
Flow - Error caught: Missing ; wrong position

### ISSUE THREAD

**Issue by aliokan** [DoclerLabs/hexMachina#284]
```
src/configuration/feature/InAppSignUpConfiguration.flow:6: characters 20-78 : Fails to retrieve pack for class named feature.signup.adapter.SignUpController'
src/configuration/feature/InAppSignUpConfiguration.flow:6: characters 20-78 : Error caught: Missing ;
```

The missing `;` is inside a Model use in SignUpController

Error position should be the flow file, but inside class

**Comment by FrancisBourre** [comment]
> Error position should be the flow file, but inside class.

What do you mean? It can't be the both. My assumption is you meant:
Error position should **NOT** be the flow file, but inside class

And the good news is it's done:
`hexModularDSL/test/hex/mock/CrashTest.hx:11: characters 10-11 : Error caught: Missing ;`
