### ISSUE TITLE
Strong restrictions to what is allowed in anonymous objects.

### ISSUE THREAD

**Issue by back2dos** [DoclerLabs/hexMachina#294]
Currently it seems like something of this kind is not possible:

```haxe
foo = new Foo({
   bar: Std.string(5)
});
```

With:

```haxe
class Foo {
    public function new(o:{ bar: String }) {}
}
```

Seems that's because [for `EObjectDecl` the field expressions are passed through `parseProperty`](https://github.com/DoclerLabs/hexDSL/blob/cee54903eba97b2ccf03ca12455aca1436a25849/src/hex/compiletime/flow/parser/expr/ArgumentParser.hx#L68) which appears to be very restricted.

Would be nice if anything that is a valid "value" in flow (i.e. can be on the right side of a declaration) would be valid in an anonymous object too.

**Comment by FrancisBourre** [comment]
I cover many more new cases. Check example below.
Don't hesitate to report some missing ones.

```
@context( name = 'applicationContext' )
{
	@public
	foo = new hex.mock.ConstructorWithAnonStruct( { s: Std.string(5) } );
	
	@public
	o = { s: Std.string(5) };
	
	@public
	o2 = { s: foo.getString() };
	
	@public
	foo2 = new hex.mock.ConstructorWithAnonStruct( { s: foo.getString() } );
	
	@public
	foo3 = new hex.mock.ConstructorWithAnonStruct( { s: closure() } );
	
	closure = foo.getString.bind();
}
```
