### ISSUE TITLE
Runtime dsl params not works correctly with interfaces

### ISSUE THREAD

**Issue by dmitry-kuzovatkin** [DoclerLabs/hexMachina#297]
For dsl
@context(
	params = {
		item: com.IClassA
        }...
if we will try to pass in class which implements com.IClassA, it will not works.

var c = new ClassA();
context.execute({item: c}), 'cause it have type ClassA

but next code will works

var c:IClassA = new ClassA();
context.execute({item: c})

**Comment by FrancisBourre** [comment]
I'm unable to reproduce it. Did you try to isolate it to see if it stills failing?

**Comment by dmitry-kuzovatkin** [comment]
Can't reproduce it any more too
