### ISSUE TITLE
Add recursive ECall parsing

### ISSUE THREAD

**Issue by gene-pavlovsky** [DoclerLabs/hexMachina#301]
This works in Flow:
```haxe
    sendLineSignal = com.utils.SignalUtil.whenEqual(chatInputModule.signal, memberapplet.feature.chat.chatinput.ChatInputSignal.SendLine);
    sendLineSignal.handle(surpriseIconModel.triggerRecommendation);
```

This doesn't (complains something about types):
```haxe
com.utils.SignalUtil.whenEqual(
    chatInputModule.signal, 
    memberapplet.feature.chat.chatinput.ChatInputSignal.SendLine
).handle(surpriseIconModel.triggerRecommendation);
```

`com.utils.SignalUtil.whenEqual` is a static function that filters a signal with a particular value.

Would be nice if it was possible to avoid creating unneeded temporary (single-use) identifiers.

**Comment by FrancisBourre** [comment]
[This commit](https://github.com/DoclerLabs/hexDSL/commit/b8679db0183a4f5302b7131ba355fa56b3685be4) covers this specific scenario, but the implementation has to be dirty for allowing the other compilers to benefit from it. I'd like to go further just for the static flow implementation and offer full method call recursivity with argument dependency graph.
