### ISSUE TITLE
BasicCommand refactoring

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMachina#66]
As BasicCommand is designed for a simple usage of the Command pattern, it should have a few changes;
- It should contain IInjectorContainer by default
- The owner property should not point to IModule, because it's irrelevant in the ApplicationContext
- It should always have a logger that is referring to the corresponding domain.

We should have the same changes for AsyncCommand

**Comment by FrancisBourre** [comment]
BasicCommand implements IInjectorContainer in 0.6.0

**Comment by FrancisBourre** [comment]
This is the[ current command class implementation](https://github.com/DoclerLabs/hexCommand/blob/master/src/hex/control/trigger/Command.hx) that fits every need for now:
