### ISSUE TITLE
Keep scope automatically in many framework tools

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMachina#71]
Now we have to pass everywhere the function scope, but it would be nice, to detect it automatically by the framework:

some examples:
<proxy id="eventProxy" type="hex.event.EventProxy">
        <argument ref="myModule"/>
        <argument ref="myModule.foo"/>
...
        </listen>

new AsyncHandler(this, _onComplete)

**Comment by FrancisBourre** [comment]
I tried to do it everywhere it was nice and possible. For now I close this issue. Maybe later I will open it again, if I find APIs that shoud get the same refact in a proper way.
