### ISSUE TITLE
Pass runtime properties to XmlCompiler.readXmlFile

### ISSUE THREAD

**Issue by grosmar** [DoclerLabs/hexMachina#76]
I would like to be able to pass runtime objects to the XmlCompiler.readXmlFile function, and register them in the ApplicationContext. 

For example initial configuration parameters that i get at runtime.

**Comment by FrancisBourre** [comment]
I spent the night to think about the ideal implementation. Here is the [final version](https://github.com/DoclerLabs/hexIoC/blob/develop/test/hex/compiler/parser/xml/XmlCompilerTest.hx#L96) where you can mix unlimited passes of compile-time and dynamic runtime assembling, in any order, and with no restriction of what you build.

I let you imagine the endless possibilities. Few examples I would like to mention:
- Get a stream from a server to add a set of objects to your context.
- A module that builds a stream during application execution to extend your context.
- Isomorphic application with objects building, states and methods calls synchronized via streams dialog.
