### ISSUE TITLE
[Travis] - use PHP >= 5.4.0 

### ISSUE THREAD

**Issue by aliokan** [DoclerLabs/hexMachina#98]

**Comment by FrancisBourre** [comment]
Can you provide a description and a status about this issue please?

**Comment by FrancisBourre** [comment]
Haxe for Travis-CI is not officially supported, but is community maintained.
Please file any issues using the following link
  https://github.com/travis-ci/travis-ci/issues/new?labels=haxe
and mention `@andyli`, `@waneck`, and `@Simn` in the issue

**Comment by FrancisBourre** [comment]
Can we close this issue?
